# Generated by Django 4.2.7 on 2023-11-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIluminacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_sensor_proximidad', models.CharField(choices=[('apagado', 'Apagado'), ('encendido', 'Encendido')], max_length=10)),
                ('estado_sensor_voltaje', models.CharField(choices=[('bajo', 'Bajo'), ('alto', 'Alto')], max_length=10)),
                ('luminosidad', models.CharField(choices=[('baja', 'Baja'), ('alta', 'Alta')], max_length=10)),
                ('politicas_iluminacion', models.TextField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.sector')),
            ],
        ),
    ]
