# Generated by Django 4.2.7 on 2023-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_dispositivoiluminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivoiluminacion',
            name='estado_sensor_voltaje',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('normal', 'Normal'), ('alto', 'Alto')], max_length=10),
        ),
    ]
