# Generated by Django 4.2.7 on 2023-11-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_dispositivoiluminacion_estado_sensor_voltaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaTrafico',
            fields=[
                ('contacto', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
