# Generated by Django 4.2.7 on 2023-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_proveedorserviciosdeemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaMantenimientoVial',
            fields=[
                ('contacto', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='dispositivoiluminacion',
            name='luminosidad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta')], max_length=10),
        ),
    ]
